language: go
sudo: false

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get -v -t ./...

script:
  - go test .            -cover -coverpkg github.com/fgrosse/goldi            -coverprofile goldi.coverprofile
  - go test ./goldigen   -cover -coverpkg github.com/fgrosse/goldi/goldigen   -coverprofile goldigen.coverprofile
  - go test ./util       -cover -coverpkg github.com/fgrosse/goldi/util       -coverprofile util.coverprofile
  - go test ./validation -cover -coverpkg github.com/fgrosse/goldi/validation -coverprofile validation.coverprofile

after_script:
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
