language: go
sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - go get -v -t ./...

script:
  - go test -cover -coverpkg github.com/fgrosse/goldi            -coverprofile goldi.coverprofile      .
  - go test -cover -coverpkg github.com/fgrosse/goldi/goldigen   -coverprofile goldigen.coverprofile   ./goldigen
  - go test -cover -coverpkg github.com/fgrosse/goldi/validation -coverprofile validation.coverprofile ./validation

after_script:
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
