language: go
sudo: false

go:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - make install

script:
  - make coverage

after_script:
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
