language: go
sudo: false

go:
  - 1.9
  - 1.10
  - 1.11
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - make install

script:
  - make coverage

after_script:
  - gover
  - goveralls -coverprofile=gover.coverprofile -repotoken $COVERALLS_TOKEN
